spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.96.27.148:3306/excel?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
  jpa:
    hibernate:
      ddl-auto: update